import { NextResponse } from 'next/server';
import { supabase } from '@/utils/supabase';
// 1. Notice the lowercase object destructuring here - this matches Google's exact library release
import { GoogleGenAI } from '@google/genai';

// 2. Fallback check to ensure the key is being read cleanly by Next.js
const apiKey = process.env.GEMINI_API_KEY;
const ai = apiKey ? new GoogleGenAI({ apiKey }) : null;

// 🔄 Changed from GET to POST to accept the incoming tenant isolation payload safely
export async function POST(request) {
  try {
    // 3. Early crash preventer if the key dropped out
    if (!ai) {
      return NextResponse.json(
        { error: 'Backend Setup Error: GEMINI_API_KEY is blank or unreadable in .env.local' },
        { status: 500 }
      );
    }

    // 🔒 Grab the specific isolated userId passing from your frontend request body
    const { userId } = await request.json();

    if (!userId) {
      return NextResponse.json(
        { error: 'Tenant isolation key (userId) is required to process budget metrics.' },
        { status: 400 }
      );
    }

    // 🔑 CRITICAL FIX: Restrict data pulling to ONLY this specific user_id handle
    const { data: transactions, error: dbError } = await supabase
      .from('transactions')
      .select('*')
      .eq('user_id', userId) // 👈 Sandbox boundary lock
      .order('transaction_date', { ascending: false });

    if (dbError) {
      console.error('Database retrieval failure inside AI router:', dbError.message);
      return NextResponse.json({ error: dbError.message }, { status: 500 });
    }

    // 3. Handle fallback state if the user's ledger is currently empty
    if (!transactions || transactions.length === 0) {
      return NextResponse.json({
        analysis: "Welcome to SmartSpend! Your transaction history is currently empty. Start logging your daily expenses and income streams, and I will step in here to map out spending patterns, flag capital burns, and generate strategic advice."
      }, { status: 200 });
    }

    // 4. Transform raw database JSON rows into an un-bloated, readable text list for the model
    const simplifiedLedger = transactions.map(t => 
      `- ${t.transaction_date} | Type: ${t.type} | Amount: ₹${t.amount} | Note: "${t.description}"`
    ).join('\n');

    // 5. Engineer a precise, context-bounded prompt following Senior engineering guidelines
    const analyticalPrompt = `
You are an expert personal finance strategist and automated budgeting coach inside the SmartSpend app.
Analyze the following user transaction data meticulously and generate actionable optimization insights.

### USER DATA ARRAY:
${simplifiedLedger}

### RULES FOR RESPONSE FORMATTING:
1. Speak direct, supportive, and action-oriented. Keep the tone engaging.
2. Provide a high-level summary sentence regarding their liquid positions or saving trajectory.
3. Deliver exactly 3 sharp, distinct bullet points highlighting noticeable patterns (e.g., heavy cash burn flags, profit margins, behavioral trends, or tactical ways to optimize recurring lifestyle spending).
4. Use neat Markdown tags for styling. Avoid generic filler statements.
`;

    // 6. Fire the structured prompt down to Google's super-fast Gemini model
    const aiResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: analyticalPrompt,
    });

    // 7. Extract the text response payload generated by the AI
    const analysisText = aiResponse.text || "Gemini could not parse an answer. Try updating your ledger rows.";

    // 8. Return the raw string back to our frontend interface safely
    return NextResponse.json({ message: 'Success', analysis: analysisText }, { status: 200 });

  } catch (catchError) {
    console.error('Critical Failure on AI Route Lifecycle:', catchError);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}